# Generated by Django 5.2.10 on 2026-04-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('estimated_order_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivery_type', models.CharField(choices=[('home', 'Home'), ('pickup', 'Pickup')], max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('programmed_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('pay_status', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30)),
                ('status_change_data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
