# Generated by Django 5.2.10 on 2026-06-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='incidences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'En persona')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_change_data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
