# Generated by Django 5.2.10 on 2026-04-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_allergen_icon_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='icon',
        ),
        migrations.AddField(
            model_name='allergen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='allergens/'),
        ),
    ]
